import streamlit as st
st.title("About Us")
st.markdown("A CV analysis using AI project is an automated system that uses Natural Language Processing (NLP) and Machine Learning (ML) to parse, rank, and evaluate job applications against job descriptions. It automates screening by extracting skills, experience, and education from resumes, eliminating manual, time-consuming tasks and reducing human bias.")
st.subheader("Key Aspects of the Project")
st.write("Automatic Parsing: Extracts structured data (skills, experience, contact info) from unstructured formats like PDF or DOCX using tools like Pyresparser")
st.subheader("Ranking & Scoring: ")
st.markdown("Compares candidates to job descriptions, scoring them based on skill matching, experience level, and education, often producing a 0-100% match score.")
st.subheader("Keyword Extraction:")
st.markdown("Detects relevant technical skills and phrases to ensure candidates meet requirements.")
st.subheader("Coding")
st.code("from PyPDF2 import PdfReader")
st.code("def extract_text(pdf_path):")
st.code("reader = PdfReader(pdf_path)text = ")
st.code("for page in reader.pages:")
st.code("text += page.extract_text()return text")
